apiVersion: apiserver.config.k8s.io/v1
kind: AdmissionConfiguration
plugins:
- name: ImagePolicyWebhook
  configuration:
    imagePolicy:
      kubeConfigFile: /etc/kubernetes/webhook/webhook.yaml
      allowTTL: 10
      denyTTL: 10
      retryBackoff: 20
      defaultAllow: true
